---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:us-east-1:905418376874:generatedTemplate/f6f3be75-4640-45c7-8c97-8387bc6af119"
Resources:
  EKSClusterCapstoneproject:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EKS::Cluster"
    DeletionPolicy: "Retain"
    Properties:
      Logging:
        ClusterLogging:
          EnabledTypes:
          - Type: "api"
          - Type: "audit"
          - Type: "authenticator"
          - Type: "controllerManager"
          - Type: "scheduler"
      ComputeConfig:
        NodePools:
        - "general-purpose"
        - "system"
        Enabled: true
        NodeRoleArn: "arn:aws:iam::905418376874:role/AmazonEKSAutoNodeRole"
      StorageConfig:
        BlockStorage:
          Enabled: true
      DeletionProtection: false
      ZonalShiftConfig:
        Enabled: true
      AccessConfig:
        AuthenticationMode: "API"
      EncryptionConfig: []
      KubernetesNetworkConfig:
        ServiceIpv4Cidr: "10.100.0.0/16"
        ElasticLoadBalancing:
          Enabled: true
        IpFamily: "ipv4"
      RoleArn: "arn:aws:iam::905418376874:role/AmazonEKSAutoClusterRole"
      Name: "capstone-project"
      UpgradePolicy:
        SupportType: "STANDARD"
      Version: "1.33"
      ResourcesVpcConfig:
        EndpointPublicAccess: true
        PublicAccessCidrs:
        - "0.0.0.0/0"
        SecurityGroupIds: []
        SubnetIds:
        - "subnet-0d1874bb0bad97f05"
        - "subnet-0c5429982c1717f69"
        - "subnet-0d318003363a85105"
        - "subnet-05615e55a552c640a"
        - "subnet-0b55f8050720f9544"
        EndpointPrivateAccess: true
  EKSAddonCapstoneprojectQ9:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EKS::Addon"
    DeletionPolicy: "Retain"
    Properties:
      NamespaceConfig:
        Namespace: "kube-system"
      ClusterName:
        Ref: "EKSClusterCapstoneproject"
      AddonName: "vpc-cni"
      AddonVersion: "v1.19.5-eksbuild.1"
  EKSAddonCapstoneproject:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EKS::Addon"
    DeletionPolicy: "Retain"
    Properties:
      NamespaceConfig:
        Namespace: "kube-system"
      ClusterName:
        Ref: "EKSClusterCapstoneproject"
      AddonName: "coredns"
      AddonVersion: "v1.12.1-eksbuild.2"
  EKSAddonCapstoneprojectY4:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EKS::Addon"
    DeletionPolicy: "Retain"
    Properties:
      NamespaceConfig:
        Namespace: "kube-system"
      ClusterName:
        Ref: "EKSClusterCapstoneproject"
      AddonName: "metrics-server"
      AddonVersion: "v0.8.0-eksbuild.2"
      ConfigurationValues: "nodeSelector:\n  karpenter.sh/nodepool: system"
  EKSAddonCapstoneprojectHc:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::EKS::Addon"
    DeletionPolicy: "Retain"
    Properties:
      NamespaceConfig:
        Namespace: "kube-system"
      ClusterName:
        Ref: "EKSClusterCapstoneproject"
      AddonName: "kube-proxy"
      AddonVersion: "v1.33.0-eksbuild.2"
