apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone 
  template:
    metadata:
      labels:
        app: capstone
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: capstone
        image: venkateshkesa/capstoneproject:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
          - -nginx.scrape-uri=http://127.0.0.1:80/stub_status
        ports:
          - containerPort: 9113
            name: metrics
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      