apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone 
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: venkateshkesa/capstoneproject:latest
        ports:
        - containerPort: 80