apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone
spec:
  type: NodePort
  selector:
    app: capstone
  ports:  
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001   