apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: capstone
  labels:
    app: capstone
data:
  nginx.conf: |   # must match subPath in Deployment
    events {}

    http {
      server {
        listen 80;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }

        location /stub_status {
          stub_status;
          allow 127.0.0.1;
          deny all;
        }
      }
    }
